version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'fabelio_app'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'root'
       MYSQL_ROOT_PASSWORD: 'root'
 web:
    build: .
    working_dir: /code/fabelio-app/
    command: gunicorn fabelio_app.wsgi -b 0.0.0.0:8000
    volumes:
      - '/static:/static'
    ports:
      - '8000:8000'
    depends_on:
      - db