# Generated by Django 2.2.6 on 2019-10-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productid',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
